### ISSUE TITLE
Need stop word lists for all supported ontologies.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#119]
OBP-250: As an admin, I want to be able to upload a text file with arbitrary terms for each vocabulary, to help reduce less meaningful search results.

We need the list of terms for at least the following ontologies:
[ ] CHEBI
[ ] ENVO
[ ] SDGIO
[ ] L05
[ ] L06
[ ] L22
[ ] WoRMS

It'd probably be easiest of those files were in csv format but whatever is easiest for now and we can decide on the format and we implement this feature.

**Comment by pbuttigieg** [comment]
A generic stack of stopwords is fine for now - you can use the NLTK library's list as described [here](https://byteiota.com/stopwords/). 

The key is to make sure this list is in a place the IODE maintainers can get to and edit easily when we want to adapt/extend it. Similar to the store of SPARQL query.

Additionally, remove all terms with <=2 characters from these ontologies.

Verify that only the class (OWL) or concept (SKOS) labels, exact synonyms, and alternative labels are being indexed for tagging.

**Comment by paulpilone** [comment]
We incorporated the list from the NLTK library.
