### ISSUE TITLE
Update citations help text.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#162]
Change to:

> To export this citation select individual record check boxes or click 'Select All' - a Download Citation box will display, click it and the records will be downloaded to your designated Download folder OR just copy and paste.

**Comment by paulineobps** [comment]
Text OK - but the font colour needs to be darker please - it is hard to read.  thanks

**Comment by paulpilone** [comment]
@paulineobps Darkened the text color:

<img width="1196" alt="Screen Shot 2022-07-06 at 9 35 27 PM" src="https://user-images.githubusercontent.com/981227/177671439-a7dfd012-31a9-4f5a-a74f-3d0c5c40e92b.png">

**Comment by paulineobps** [comment]
this is how it looks to me at 7 Jun 19.23 UTC

[cid:8fa4a23d-dba4-41a4-bc9d-ef00cab528bb]

Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, Wandelaarkaai 7/61, 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
@paulineobps This is now on develop: https://d2fdejtifs20g8.cloudfront.net/

**Comment by paulineobps** [comment]
Thanks Paul - OK to CLOSE - still would prefer it darker  (in fact that is a comment for the whole site about using grey - but that is for another conversation!)
