### ISSUE TITLE
Update copy on first visit screen.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#164]
REWORD:

> The Ocean Best Practices System (OBPS)  is a secure, permanent global repository of ocean research, operations, data/information management and applications methodologies  (also known as “BestPractices”) **  The OBPS  invites the ocean community to submit their own methodologies  to share globally with their colleagues.

> Please note, unless it is annotated as Endorsed by an Expert Panel, inclusion of a methodology in OBPS does not indicate a recommendation by OBPS.
> __________________________________________________________________________________
> (Please Make this smaller font size)** A Best Practice is defined as “a methodology that has repeatedly produced superior results relative to other methodologies with the same objective”. To be fully elevated to a best practice, a promising method will have been adopted and employed by multiple organizations.

**Comment by paulineobps** [comment]
**The text has not been changed it should be:**
The Ocean Best Practices System (OBPS)  is a secure, permanent global repository of ocean research, operations, data/information management and applications methodologies  (also known as “BestPractices”) **  The OBPS  invites the ocean community to submit their own methodologies  to share globally with their colleagues.

Please note, unless it is annotated as Endorsed by an Expert Panel, inclusion of a methodology in OBPS does not indicate a recommendation by OBPS.
__________________________________________________________________________________
** A Best Practice is defined as “a methodology that has repeatedly produced superior results relative to other methodologies with the same objective”. To be fully elevated to a best practice, a promising method will have been adopted and employed by multiple organizations."   (make this smaller font size)

This is what is on development at the moment
![image](https://user-images.githubusercontent.com/24316483/178088292-bcb0b6b0-ff25-4d0a-aad8-35d6063aaf4a.png)

**Comment by paulpilone** [comment]
@paulineobps I've fixed this - sorry about that. Not sure How I missed that middle text. I'll deploy it once it's merged into `develop`.

![image](https://user-images.githubusercontent.com/981227/178296127-d7f85713-a198-48eb-a32f-3e9d3cf6ff93.png)

**Comment by paulpilone** [comment]
@paulineobps Deployed to dev: https://d2fdejtifs20g8.cloudfront.net/
