### ISSUE TITLE
Update Contact Us link.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#166]
Should go to: https://repository.oceanbestpractices.org/feedback

**Comment by paulpilone** [comment]
@arnounesco The website is correctly linking to the URL in the description but that results in an Internal Server Error served from repository.oceanbestpractices.org.

**Comment by paulineobps** [comment]
Have emailed arno with this request on 5 July 2022

**Comment by paulineobps** [comment]
on dev server 'contact us' still going to internal server error
@arnounesco

**Comment by paulpilone** [comment]
@paulineobps It looks like if you click the link in my first comment (https://repository.oceanbestpractices.org/feedback) you still get a 500 error.

**Comment by paulineobps** [comment]
Arno says the moment that the original page from where the link starts is something like search.oceanbestpractices.org it will be fine, nothing should be done from their side anymore
