### ISSUE TITLE
Search term is removed when the user chooses a search option.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#170]

**Comment by paulineobps** [comment]
You can enter the term and then switch on Endorsed filter, but the result was 3 (there are 5 formally endorsed by GOOS). 
WHAT METADATA FIELD/S ARE YOU USING FOR THE ENDORSED FILTER

**Comment by paulpilone** [comment]
@paulineobps We're using `obps_endorsementExternal_externalEndorsedBy`. Since there are only 5 documents would it be possible to send over the handles or UUIDs of those documents? I can verify that they're indexed correctly that way.

I know we're missing a few documents due to another issue I've already filed so it's possible they're just missing from the index and the filter is working correclty.

**Comment by paulineobps** [comment]
selecting subject term and turning filter option on, now works - does not delete the subject term in search box .
endorsed records retrieved seems to be data in the wrong metadata field issue.
OK CLOSED
