### ISSUE TITLE
Privacy policy is out of date and needs to be updated.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#175]
Need OBPS to provide new privacy policy or we can remove it altogether if we're not going to require one anymore.

**Comment by paulineobps** [comment]
ARNO WILL REPLACE THE POLICY STORED AT https://repository.oceanbestpractices.org/page/policy  - with the new text  at https://docs.google.com/document/d/1P6syL1WPYFfe76Gny-0VmkNQaWUwqmEdDCFtycb7hXo/edit?usp=sharing.  YOUR LINK ON EDS WILL GO TO THIS UPDATED VERSION I BELIEVE

**Comment by paulpilone** [comment]
@paulineobps That is correct. The Privacy Policy link on the landing page links to https://repository.oceanbestpractices.org/page/policy so the user will see any changes made to that page.

Going to close this ticket since there's not change required in our application.

**Comment by paulpilone** [comment]
Decided to reopen this and assign to @arnounesco.

**Comment by arnounesco** [comment]
https://github.com/iodepo/dspace-obps/issues/26
