### ISSUE TITLE
Remove "OceanKnowledge Tagger" from "Submit Best Practices" drop down.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#176]

**Comment by paulineobps** [comment]
OK - BUT reCAPTCHA has a error.  
When you click to select OCEANKNOWLEDGE TAGGER It opens but there is no obvious way to close it (except if you know to click on the OBPS logo takes you to the landing page)

**Comment by paulpilone** [comment]
@paulineobps The reCAPTCHA will not work in dev because it's configured based on a specific domain (search.oceanbestpractices.org). Since dev uses a generic CloudFront URL (d2fdejtifs20g8.cloudfront.net) the reCAPTCHA shows an error. A few thoughts here:

- I don't think the search bar should appear on this page.
- Figure out whether we should hide the reCAPTCHA on develop or if we can configure it with a develop and production domain name.
- Determine a way to make navigation back to the landing page more obvious than just the OBPS logo or back button.
- We should really verify that this page still works as expected. It's been awhile since we've tested this feature.

However, I think we should file a new issue for this and page since it's out of scope of the original request this Issue describes. I'll file that issue but I don't think we should hold up deployments because of it.

**Comment by paulpilone** [comment]
Created #227 to track the issues I mentioned in my previous comment.

**Comment by paulineobps** [comment]
Agree with all your above comments.  I tried tagger in production and does not work there
