### ISSUE TITLE
Update Search Tips to reflect new features.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#180]
I've shared a document with @paulineobps which includes the existing copy. We can use this Google document to coordinate updated copy and add it the source code.

**Comment by paulineobps** [comment]
Am working on it see https://docs.google.com/document/d/16x1tlty2ieuplXNPCzfYIpY_yA8rZZVdWi_Twm4Mjl4/edit?usp=sharing.  A little more to do with new search parameters particularly Endorsed which is problematic.   There will be a couple of extra images/screenshots needed

**Comment by paulineobps** [comment]
Text is updated.  but need  a couple of images replaced or added. by you  I was going to bookmark the contents and sections, but maybe  there is no point because you will not be uploading this as a 'document'.  Let me know otherwise it is finished

**Comment by paulpilone** [comment]
@brianandres2 Let me know if you can't access that Google Doc.

**Comment by paulpilone** [comment]
Closed with PR #243

**Comment by paulineobps** [comment]
Thanks Paul

I will go through this carefully today, particularly images but initial comments

  1.  Formatting - The text is way too small - can it not be the same as the original Search Tips you did?
  2.  Formatting - Spacing between sections too much ; and image positions need work
  3.  The contents list needs to be linked (clickable) to take users to the correct section

thanks

Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, Wandelaarkaai 7/61, 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________
