### ISSUE TITLE
Search term breadcrumbs should convey the search field scope to which they apply.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#181]
When the user enters additional search fields in the search results page the field is eventually displayed as a breadcrumb underneath the search bar. However, each field could be applied to a different search field but the user has no way of knowing that.

For example in the attached screenshot each of the search fields I entered correspond to the similarly named metadata field, however, there's no visual way for the user to know that other than just remembering how they searched. It'd be nice to have some visual cue indicating which metadata field the search field is applied to.
<img width="492" alt="Screen Shot 2022-05-16 at 11 16 41 PM" src="https://user-images.githubusercontent.com/981227/168721558-55e469b1-00da-48cf-81e8-6c21cfc1713b.png">

**Comment by paulpilone** [comment]
This is _technically_ possible now due to the work done in #190. Search keywords now have information about the field they're scoped too. Should be able to use those to render the field in these breadcrumbs.

**Comment by paulineobps** [comment]
Boolean operators only display when you add a new term to the original search - 

 Please enhance the help wording  to 'All terms listed affect current search. Clear them to start a new search **or add a second term and use the Boolean operators then displayed'"**

**Comment by paulpilone** [comment]
@paulineobps Updated hint text:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/981227/177672684-3ee3013d-ff3f-4af6-b44f-679a390d4e08.png">

**Comment by paulineobps** [comment]
Yes great - can see now when you combine search in two different metadata fields BUT not seeing the additional text - still showing  **All terms listed affect current search. Clear them to start a new search.**  - does it take time for new edits to display?
![image](https://user-images.githubusercontent.com/24316483/177860048-960c4d98-2c6e-475f-b268-258f8a585c1c.png)

**Comment by paulpilone** [comment]
@paulineobps This is now on develop: https://d2fdejtifs20g8.cloudfront.net/

**Comment by paulineobps** [comment]
additional text displayed Thanks OK CLOSE
