### ISSUE TITLE
Boolean operators are not returning expected results.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#182]
From the bug filed:

Boolean operators are not correct: on the landing page search for 'arno', this will give you a list of documents (6) in the search results. Finetune your search at the top of the page and choose 'author', type 'arno' again and search. This results (according to the information under the search field at the top of the page) in 'document with the word "arno" where-ever in the text OR documents with "arno" as author), so there should be at least 6 results again, only ONE shown

**Comment by paulpilone** [comment]
Related to #190

**Comment by paulpilone** [comment]
Since #190 has been merged I think it's worth revisiting this ticket to see if we still have this issue.

**Comment by paulpilone** [comment]
@paulineobps Could we test this again to see if boolean operators are working as expected?

**Comment by paulineobps** [comment]
this type query working now OK CLOSE
