### ISSUE TITLE
Search is not matching plural versions of a search field.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#184]
From the bug report:

I searched for transmissometer expecting to pick up 'Best Practices for Shipboard Underway Transmissometers. Version ONE.'  I searched in Title and All Fields but it did not find it - but does if I search for transmissometers

**Comment by paulineobps** [comment]
Plural and singular not being found  in Title or All Fields. eg  Measurement

**Comment by paulpilone** [comment]
@paulineobps I'll see if I can tweak the documents index to stem words in the fields we search and improve the singular/plural results.

**Comment by paulpilone** [comment]
Explore using the stemmer analyzer at index to see if this improves plural searches: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/analysis-stemmer-tokenfilter.html.

I'm a little concerned that might grind index to a halt but it's worth testing.

**Comment by paulineobps** [comment]
in Search Tips
'Partial matches will be included in the results (e.g. a query like “mangroves” will also retrieve “mangrove”)'

the above is not working ie search does not include singular and plural

**Comment by paulpilone** [comment]
Quick note: this will not work on dev yet until I re-index documents. I'll update this ticket when that's done so we can test it.
