### ISSUE TITLE
Add help text to inform user that only the current page of results will be included in a generated citation file.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#188]
From the bug report:

When you select all and there is more than one screen, the select all is not applied to the second screen
NEED SOME TEXT TO REMIND USER

**Comment by paulineobps** [comment]
Do not see the added text?

**Comment by paulpilone** [comment]
@paulineobps The hint appears when you hover over "Select All". We use this same interaction for the hint text on the search field scopes:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/981227/177673327-00ba903e-89d9-4ce1-9b66-208e6e7a5a1e.png">

**Comment by paulineobps** [comment]
OK THANKS CLOSE
