### ISSUE TITLE
Landing page descriptions of terminologies

### ISSUE THREAD

**Issue by pbuttigieg** [iodepo/OceanBestPractices#20]
Visible button on landing page providing explanation of what terminologies (ontologies, thesauri, etc) are.

**Comment by justinykuo** [comment]
Hey @pbuttigieg!

If you have the explanations of what the terminologies are, I'm happy to take this. 

Additionally, how would you like the terminologies displayed? E.G. In a modal (like the `disclaimer`)?  And where would you like the button?

Attached image for suggestion/reference 

![Screen Shot 2019-12-10 at 21 41 10 PM](https://user-images.githubusercontent.com/26318431/70587001-c73e1380-1b96-11ea-9dca-6a7f2f7950e2.png)

**Comment by pbuttigieg** [comment]
Hi @justinykuo - thanks!

We had some text from the Polar Data Forum that would work for now:

>Controlled vocabulary
A list of terms controlled by some authority - e.g. a dropdown list.
Glossary
A collection of terms and their definitions, possibly with synonyms - e.g. NSIDC's Cryosphere Glossary: https://nsidc.org/cryosphere/glossary 
Thesaurus
A structured controlled vocabulary where each term is annotated with information and/or metadata (e.g. definition, source) and its hierarchical, associative, or equivalence relationships to other terms in the thesaurus. 
Taxonomy
A hierarchy of terms organized as a tree structure without formal relationships to terms in other trees. Terms that are deeper in the tree (i.e. towards the leaves) may gain and lose properties relative to their ancestors.
Ontology
A formal representation of knowledge, typically in a graph or network structure,  with both human and machine-readable definitions, with logical relationships (axioms) between the terms, which together define a domain of knowledge.


I'd have a button that brings up that description somewhere in the Terminology list: 

![image](https://user-images.githubusercontent.com/2276146/70921857-5dee5280-2025-11ea-9a05-33f05ae3749f.png)

Obviously a smaller question mark bubble as superscript on "Terminologies"

Clicking that would bring up the descriptions in a box similar to the terminology list box

**Comment by justinykuo** [comment]
Hey @pbuttigieg ,

Here's the PR for this: https://github.com/iodepo/OceanBestPractices/pull/31

I tried to attach a screen recording, but I'm not sure if it went through. Thanks!

**Comment by paulpilone** [comment]
Closing this because the work was merged in awhile ago.
