### ISSUE TITLE
Add new E84 team member as a contributor to the project.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#203]
We have an intern that can contribute to this project. In order to push changes and open PRs can they be added as a Collaborator to the project?

**Comment by paulpilone** [comment]
Getting his username - will update this ticket as soon as I do.

**Comment by paulpilone** [comment]
Github user: brianandres2
Email: bandres@element84.com

**Comment by arnounesco** [comment]
done, @paulpilone @brianandres2 please check and close ticket if ok

**Comment by paulpilone** [comment]
Thanks @arnounesco! I'll work with Brian and we'll get this tested.
