### ISSUE TITLE
it's Istanbul, it's Constantinopel

### ISSUE THREAD

**Issue by arnounesco** [iodepo/OceanBestPractices#209]
Mini-putin has decided that the name of his country in enlish sound to much as a stupid (american) bird and because there are no other more ugent issues to tackle demands that the whole world changes Turkey to Türkiye, yes indeed with the wellknown english letter ü

**Comment by paulpilone** [comment]
@arnounesco Are there references to Turkey in the application? I did a quick search in the repo and couldn't find any.
