### ISSUE TITLE
Make pull request reviews optional.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#229]
Thanks for making `develop` a protected branch! Ideally, we'd require reviews on pull requests before merging. However, it's likely I'll be the only developer making code changes. When @brianandres2 returns to school I won't be able to merge any code into `develop` because pull request reviews are currently required.

Could we make pull requests optional? I believe the settings should end up looking like:

![image](https://user-images.githubusercontent.com/981227/177812819-7e96e8f0-404e-4e88-b8aa-d0873aedd413.png)

I'd like to keep status checks passing as a requirement for pull requests because we don't want to be committing any code that breaks a test.

**Comment by paulpilone** [comment]
We'll probably need these same settings on `master` too.

**Comment by paulpilone** [comment]
I suppose another option here is to bump my privileges up in the repository (I _think_ admin bypasses the required review rule) but I understand if you don't want to do that.

**Comment by arnounesco** [comment]
I have removed the branch protection rules for now, so no pull requests required for dev or master

**Comment by paulpilone** [comment]
Thanks Arno, this is working now.
