### ISSUE TITLE
Filter Options select on search results page should display "Endorsed" if the Endorsed filter is toggled on.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#237]
Currently on the search results page if you have any filter option toggled "On" the button turns blue. Clicking the button displays a dropdown with possible filters and their status.

Instead of forcing the user to click the button to view the toggled filters we should display the filter name within the "Filter Options" box.

e.g. In this situation the blue button that says "Filter Options" should show that Endorsed is toggled on without having to actually click it: 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/981227/183537800-fd8d8d6b-c06f-4cd5-b7c5-acd1979ff7ea.png">

**Comment by paulineobps** [comment]
Yes the above requirement spec is good

**Comment by paulpilone** [comment]
Done #242
