### ISSUE TITLE
Record numbers in PROD and DEV out by 100

### ISSUE THREAD

**Issue by paulineobps** [iodepo/OceanBestPractices#254]
Paul you know this because you have mentioned it, but I cannot find the original request.  I know you have reindexed more than once but

The PRODUCTION indicates 1703 records

The DEV  indicates 1605

**Comment by paulpilone** [comment]
This is probably due to #221. I've fixed that issue but have not re-indexed yet.

**Comment by paulpilone** [comment]
#221 has been deployed on on reindex the document count was at 1703. I think we can close this?

**Comment by paulineobps** [comment]
Yes close -  I have added 2 docs since you reindexed
