### ISSUE TITLE
new Search interface Stats display stuck at 1705

### ISSUE THREAD

**Issue by paulineobps** [iodepo/OceanBestPractices#257]
new production Search interface Stats display stuck at 1705 - it should be showing 1708
![image](https://user-images.githubusercontent.com/24316483/188141243-570d082d-5bd6-4461-a1b2-ad5e38dae613.png)

**Comment by paulineobps** [comment]
20 Sep - stats still not displaying the uptodate number (1718)  BUT also new deposits  from number 1706 onwards are not findable. Email sent directly to Brandon

**Comment by paulpilone** [comment]
@paulineobps The cron lambda is running but it hasn't indexed any documents since 9/1. I just ran it again and forced it to index the documents currently published to the feed (which worked). I've reset the timer and will keep an eye on whether or not it stops indexing. I'm not 100% sure why it wasn't finding documents despite the dev function working.

**Comment by paulineobps** [comment]
Paul a special thank you .   I dare not ask why on our website [****](https://www.oceanbestpractices.org/) it shows 1718 and on the search interface 1715 .  So far I have been able to find the latest deposits..  Thank you for the fix and fingers crossed the cron continues to work.   I will add some new deposits to test.

**Comment by paulpilone** [comment]
I think that's a side effect of using the RSS feed to ingest documents. It looks like the feed only has at most ~6 documents listed so if the ingester missed some (it didn't index anything since 9/1) and they were removed from the feed we don't have any other way to discover new documents. I can run the bulk indexer later to make sure we discover which 3 were missed.

**Comment by paulineobps** [comment]
I have added a new deposit and it is findable and the total increased by one, thanks Paul.  Is there anything I can do in the deposit flow to better support this feed and index process?

**Comment by paulineobps** [comment]
I tell a lie! apologies

I can find all the 'old' deposits that were not showing or counted but I cannot find the new deposit from yesterday [**A Survey of Underwater Acoustic Data Classification Methods Using Deep Learning for Shoreline Surveillance**.](https://repository.oceanbestpractices.org/handle/11329/2072) and the stats have not moved to 1716 (on AWS)

**Comment by paulpilone** [comment]
@paulineobps I've made changes to the RSS reader that I hope improves its reliability. I'm going to push that to dev now and if everything looks ok I'll eventually push it to prod.

**Comment by paulpilone** [comment]
@paulineobps Deployed this change to both develop and production. Both are showing 1718 documents now. I think we can close this issue if you feel like new documents are being indexed correctly.

**Comment by paulpilone** [comment]
Scratch that: prod shows 1715 which is inline with missing a few. I'll run the bulk indexer and it should catch them all. I believe the changes I made to the RSS reader should fix missing documents as they're published.

**Comment by paulineobps** [comment]
Thanks Paul really appreciate you getting this sorted.  Fingers crossed the bulk indexer gets us to 1719 and we can search and find the last deposit (A Survey of Underwater Acoustic Data Classification<https://repository.oceanbestpractices.org/handle/11329/2072> ...)

I have a hurricane soon to loom over us, so am rushing around with 'battening down the hatches'.  No reply to your Github messages is because of that only.    Arno is working in Barcelona for a week, so I will try to contact him re the permissions and access questions you posed.


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulineobps** [comment]
AWS/EDS still showing 1715 so no regular updating

**Comment by paulpilone** [comment]
@paulineobps were these new documents that were published to the RSS feed? I see that the feed ingester ran today and queued a few documents up for indexing:

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/981227/192834360-484cfb0d-c5b4-4d2e-9a21-377e4e04d574.png">

**Comment by paulineobps** [comment]
Thanks Paul .  This is the last one input yesterday  https://repository.oceanbestpractices.org/handle/11329/2073 at

2022-09-27T21:20:42Z


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulineobps** [comment]
Still showing 1715 and search for latest deposits does not find the titles


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
This issue should be resolved by the work done in #280. That Issue addresses deleting and updating items which should help keep the total documents number in line.

**Comment by paulineobps** [comment]
Yes thanks the numbers are now in line.


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________
