### ISSUE TITLE
Explore Document tab does not open a document

### ISSUE THREAD

**Issue by paulineobps** [iodepo/OceanBestPractices#260]
Any AWS/EDS search result record if I click on Explore Document - it just shows the screen but it is not populated with the full text file

**Comment by paulpilone** [comment]
@paulineobps Deployed a fix to dev and prod. This should now be working: 
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/981227/192844677-b090ca50-5101-489e-9e26-6d9c0d36d03a.png">

**Comment by paulineobps** [comment]
Thanks Paul - tested and works


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________
