### ISSUE TITLE
Deposit count not increasing on feed to OBPS website

### ISSUE THREAD

**Issue by paulineobps** [iodepo/OceanBestPractices#262]
Deposit count not increasing on feed to OBPS website https://www.oceanbestpractices.org/.  Believe it should now be displaying 1722.
Note Paul P has had issues with getting the deposit count displaying on the AWS for some time but this website page count has only just stopped.

**Comment by paulineobps** [comment]
This is still showing 1715 and the count on dspace is 1724 (and none of the titles are searchable on AWS EDS.)    Any news on a solution please.  To keep the EDS searchable for latest submissions eg. Joint Cetacean Data Programme (JDCP), Data Standard: Core Data Fields and Vocabulary Guidance, Version 1.2.](https://repository.oceanbestpractices.org/handle/11329/2078)
can we manually run the process until this automatic feed is working - is this something Arno can do,?

**Comment by paulpilone** [comment]
Closing this issue since we've made changes to address this over the past year.
