### ISSUE TITLE
Update the search results boolean logic.

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#291]

**Comment by paulpilone** [comment]
@paulineobps I've been asked by Jay to make this change but I don't know what needs updating. Any help from you or Jay would be appreciated.

**Comment by arnounesco** [comment]
https://github.com/iodepo/OceanBestPractices/issues/276
https://github.com/iodepo/OceanBestPractices/issues/275
https://github.com/iodepo/OceanBestPractices/issues/236
https://github.com/iodepo/OceanBestPractices/issues/183
https://github.com/iodepo/OceanBestPractices/issues/22

Pauline has a document with all comments on the search boolean logic

**Comment by paulineobps** [comment]
Paul the Boolean search is not producing correct results;  Here is an example
![image](https://github.com/iodepo/OceanBestPractices/assets/24316483/6c6d3419-5ca5-4f97-992d-a013f8a2e7ab)

**Comment by paulineobps** [comment]
just answered


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson

ORCID: https://orcid.org/0000-0003-2551-5740<https://orcid.org/0000-0002-3237-4547>


<http://www.iode.org>


________________________________

**Comment by paulineobps** [comment]
Hi Paul - see my answer on 17 October -what ore do you need?  thanks P.

**Comment by paulpilone** [comment]
@paulineobps Looking into the author/title issue now. If you can provide an exact title and author example that'd be helpful. Also, there is another Issue related to searching with semi colons causing an error and returning 0 results. I'll look into that separately but pull it into this Milestone.

**Comment by paulpilone** [comment]
@paulineobps Testing this for awhile this afternoon trying to understand what's going on and I finally figured it out. When you search by "Title" in the user interface the backend actually searches by `dc.title`  and `dc.title.alternative`. In your example the document doesn't have an alternative title so you end up with a search that looks like `AUTHOR: Pearlman AND TITLE: Jerico AND TITLE_ALTERNATIVE: Jerico` which returns 0 results. I'll look into fixing this.
