### ISSUE TITLE
Search on EDS has stopped working ( and stats not displaying (again

### ISSUE THREAD

**Issue by paulineobps** [iodepo/OceanBestPractices#297]
Search on EDS has stopped working ( and stats not displaying (again

Arno please can you upgrade the AWS subscription - we have already said OBPS will cover it

**Comment by paulpilone** [comment]
@paulineobps I believe this was related to Elasticsearch. Can we close it since we've increased the instance size and things look stable?

**Comment by paulpilone** [comment]
Actually it looks like you already answered this in #284. Marking this as a duplicate and closing it.
