### ISSUE TITLE
Deleting records from EDS

### ISSUE THREAD

**Issue by paulineobps** [iodepo/OceanBestPractices#303]
Dear Arno

Now it is not possible to delete/withdraw  a record from DSpace and it is also deleted on EDS,  E84 have defined a process.  I attach the instructions see pdf file  and also the internal records numbers for two records that have been withdrawn from DSpace and need deleting from EDS

**DELETE FROM EDS**    
     
  **dc1ef50c-298c-409b-91ac-54a8be75f776**     

  Mariani ,P., Bachmayer,   R., Kosta,S.,   Pietrosemoli, E., Ardelan,   M.V.,   et al (2021) Collaborative   Automation   and IoT Technologies for   Coastal   Ocean Observing Systems.   Frontiers in Marine   Science, 8:647368. 8pp.    DOI:  https://doi.org/10.3389/fmars.2021.647368 |  
-- | --

**5e108f1f-995d-4bae-8366-5a0c88d59b9d**

Horning, M., Andrews, R. D., Bishop, A. M., Boveng, P. L., Costa, D. P., Crocker, D. E., ... and Womble, J. N. (2019) Best practice recommendations for the use of external telemetry devices on pinnipeds. Animal Biotelemetry, 7(20), 17pp., DOI: https://doi.org/10.1186/s40317-019-0182-6

[Deleting record from EDS.pdf](https://github.com/iodepo/OceanBestPractices/files/13846686/Deleting.record.from.EDS.pdf)

**Comment by paulineobps** [comment]
ALSO DELETE FROM EDS

e1e03757-c22a-4302-b10c-efa3cb8d8854

Intergovernmental Oceanographic Commission (1991) Manual on International Oceanographic Data Exchange. Revised edition, 1991. Paris, France, UNESCO,  84pp. (Intergovernmental Oceanographic Commission Manuals and Guides; 9). DOI: https://doi.org/10.25607/OBP-1430

  **|81a4002d-d385-41ff-9c13-e779b7105c70**

Intergovernmental Oceanographic Commission (1987) User Guide for the Exchange of Measured Wave Data.  Paris, France, UNESCO, 82pp. (Intergovernmental Oceanographic Commission Manuals and Guides; 18).  DOI: https://doi.org/10.25607/OBP-1405

**Comment by arnounesco** [comment]
All 4 documents have been removed from the search.

***REMARK*** as often is the case with the documentation we receive for the EDS, the description given in the PDF is ***NOT*** correct. Executing the giving command gives 
```

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: outfile
```
That was easy to fix, but fixing this gave me:
```
An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Could not parse payload into json: Invalid UTF-8 middle byte 0x75
 at [Source: (byte[])"��u�^����O[�V�熼m����"; line: 1, column: 5]
```

 So I lost another 2 hours to get this working. 

Just for future reference, I made a page in our internal WIKI describing the correct CLI command to delete a document from EDS. (http://wiki.iode.vliz.be/index.php/Deleting_Documents_from_OBPS_search).

**Comment by paulineobps** [comment]
Thank you very much Arno. for sorting this out.    I am unable to get to the Internal WIKI (server not found), but assume this is a process that can only be done by you - if I could do it  I would not take your time.  Thanks again

**Comment by paulpilone** [comment]
Hey Arno,

Apologies for that example Invoke command in the documentation. I just
pushed a quick documentation change that adds the required outfile argument
to the command:
https://github.com/iodepo/OceanBestPractices/tree/develop/ingest#deleting-documents

Please feel free to update the documentation in addition to your wiki. The
more eyes on the documentation the better!

Paul
