### ISSUE TITLE
To provide Arctic view on repository make links

### ISSUE THREAD

**Issue by paulineobps** [iodepo/OceanBestPractices#40]
https://arcticpractices.org  ::  link to https://repository.oceanbestpractices.org/handle/11329/1291
https://arcticpractices.net  ::    link to https://repository.oceanbestpractices.org/handle/11329/1291
https://arcticpracticespilot.org ::  link to https://repository.oceanbestpractices.org/handle/11329/1291
https://arcticpracticespilot.net ::  link to https://repository.oceanbestpractices.org/handle/11329/1291

**Comment by paulineobps** [comment]
Believe this has been **done**?

**Comment by arnounesco** [comment]
this has been done
