### ISSUE TITLE
Please add to .org the Unesco Privacy Policy

### ISSUE THREAD

**Issue by arnounesco** [iodepo/OceanBestPractices#6]
Please add to .org the Unesco Privacy Policy Unesco Privacy Policy: https://en.unesco.org/this-site/our-online-privacy-policy http://www.unesco.org/new/en/terms-of-use/terms-of-use/privacy/

**Comment by arnounesco** [comment]
where to place it : for .ORG link alongside Disclaimer ON bottom bar

**Comment by paulineobps** [comment]
see GitHub 175
